//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timmethy.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timmethy.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] bonsai {
            get {
                object obj = ResourceManager.GetObject("bonsai", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap by_nc_sa_eu {
            get {
                object obj = ResourceManager.GetObject("by_nc_sa_eu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Random Access Memory Files (*.tram)|*.tram ähnelt.
        /// </summary>
        internal static string FileDialogFilterStringMacroCodeFile {
            get {
                return ResourceManager.GetString("FileDialogFilterStringMacroCodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Micro Program Memory Files (*.tmpm)|*.tmpm ähnelt.
        /// </summary>
        internal static string FileDialogFilterStringMicroCodeFile {
            get {
                return ResourceManager.GetString("FileDialogFilterStringMicroCodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timmethy Project Files (*.tproj)|*.tproj ähnelt.
        /// </summary>
        internal static string FileDialogFilterStringProjectFile {
            get {
                return ResourceManager.GetString("FileDialogFilterStringProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] johnny {
            get {
                object obj = ResourceManager.GetObject("johnny", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to abort the pending execution? ähnelt.
        /// </summary>
        internal static string MessageBoxTextAbortPendingExecution {
            get {
                return ResourceManager.GetString("MessageBoxTextAbortPendingExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End of micro program memory reached. Stopping the current record... ähnelt.
        /// </summary>
        internal static string MessageBoxTextEndOfMicroProgramMemoryReached {
            get {
                return ResourceManager.GetString("MessageBoxTextEndOfMicroProgramMemoryReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Due to visualization reasons the macro name should not be longer than six chars ähnelt.
        /// </summary>
        internal static string MessageBoxTextMacroNameTooLong {
            get {
                return ResourceManager.GetString("MessageBoxTextMacroNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The macro name should be at least two chars long! ähnelt.
        /// </summary>
        internal static string MessageBoxTextMacroNameTooShort {
            get {
                return ResourceManager.GetString("MessageBoxTextMacroNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a macro defined at the specified address.
        ///Do you really want to override it? (This can not be undone!) ähnelt.
        /// </summary>
        internal static string MessageBoxTextMacroOverride {
            get {
                return ResourceManager.GetString("MessageBoxTextMacroOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save the project before you quit? ähnelt.
        /// </summary>
        internal static string MessageBoxTextSaveProjectBeforeQuitting {
            get {
                return ResourceManager.GetString("MessageBoxTextSaveProjectBeforeQuitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Either the file you are trying to load is corrupt or not compatible with this version of Timmethy.
        ///Please contact me via email so that i can look into it and maybe add support. ähnelt.
        /// </summary>
        internal static string MessageBoxTextSerializationErrorOnLoad {
            get {
                return ResourceManager.GetString("MessageBoxTextSerializationErrorOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected serialization error.
        ///Help me to improve this software and fix errors by simply sending the information below via e-mail:
        ///(Press CTRL+C on the keyboard to copy)
        ///SerializationException message:
        ///{0}
        ///StackTrace:
        ///{1} ähnelt.
        /// </summary>
        internal static string MessageBoxTextSerializationErrorOnSave {
            get {
                return ResourceManager.GetString("MessageBoxTextSerializationErrorOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You seem to be unauthorized to {0} that file. Relaunch the program with elevated permissions or check the file permissions and access rights. ähnelt.
        /// </summary>
        internal static string MessageBoxTextUnauthorizedFileAccess {
            get {
                return ResourceManager.GetString("MessageBoxTextUnauthorizedFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timmethymodepanelbg {
            get {
                object obj = ResourceManager.GetObject("timmethymodepanelbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timmethypanelbg {
            get {
                object obj = ResourceManager.GetObject("timmethypanelbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timmethypanelbgdis {
            get {
                object obj = ResourceManager.GetObject("timmethypanelbgdis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
